version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: urlshortener-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: urlshortener
    volumes:
      - mongodb_data:/data/db
    networks:
      - urlshortener-network

  app:
    build: .
    container_name: urlshortener-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/urlshortener?authSource=admin
      - BASE_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - urlshortener-network

volumes:
  mongodb_data:

networks:
  urlshortener-network:
    driver: bridge
